services:
  wre-builder:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WIFI_SSID=${WIFI_SSID:-your_wifi_ssid}
      - WIFI_PASS=${WIFI_PASS:-your_wifi_password}
    volumes:
      - .:/project
    # Override command if you want to run interactively
    # command: /bin/bash
